web Token
Kalixone/BookstoreAPP pull request #11
Opened 2024-03-16 15:46 UTC by Kalixone

2024-03-17 15:17 UTC, okuzan requested changes

2024-03-17 15:17 UTC, okuzan commented on src/main/java/mate/academy/springbootintro/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(BEGIN_INDEX);
```suggestion
            return bearerToken.substring(BEGIN_PREFIX.length());
```
you don't need the separate constant, they are connected

2024-03-17 15:17 UTC, okuzan commented on src/main/java/mate/academy/springbootintro/config/SecurityConfig.java
> +                                        "api/auth/login")
```suggestion
                                .requestMatchers(HttpMethod.POST, "/api/auth/**")
```

2024-03-21 12:46 UTC, nowickimj approved these changes

2024-03-21 18:54 UTC, merged