Order exercise
Kalixone/BookstoreAPP pull request #16
Opened 2024-04-20 15:45 UTC by Kalixone

2024-04-22 09:36 UTC, nowickimj requested changes

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/dto/OrderRequest.java
> +        String shippingAddress
No validation here?

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/dto/UpdateOrderStatusRequest.java
> +        Order.Status status
No validation here?

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +import lombok.Data;
You only added import but I don't see you using this annotation here.

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/model/Order.java
> +    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL)
adding `orphanRemoval = true` might be useful here

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/model/Order.java
> +    @ManyToOne
Use lazy fetching

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/model/OrderItem.java
> +    @JoinColumn(name = "book_id", nullable = false)
Consider using lazy fetching.

2024-04-22 09:36 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/service/OrderServiceImpl.java
> +        User user = userRepository.findById(userId)
Use `getReferenceById` so you don't need additional optional handling. This comment applies to all cases below.

2024-04-22 09:36 UTC, nowickimj commented on src/main/resources/db/changelog/changes/11-create-orders-table.yaml
> +                  type: decimal
Provide precision here.

2024-04-22 09:36 UTC, nowickimj commented on src/main/resources/db/changelog/changes/12-create-order-items-table.yaml
> +                  type: decimal
Provide precision here.

2024-04-22 09:36 UTC, nowickimj commented on src/main/resources/db/changelog/changes/11-create-orders-table.yaml
> +                  type: tinyint
Why tinyint? Shouldn't you consider using enum or at least varchar here?

2024-04-23 12:48 UTC, d1sam requested changes
Good job, but there are some changes, that should be done according my comments.

2024-04-23 12:48 UTC, d1sam commented on et --hard 64d14ba
please remove this file

2024-04-23 12:48 UTC, d1sam commented on src/main/java/mate/academy/springbootintro/controller/OrderController.java
Pagination should be implemented for all endpoints where list is returned

2024-04-23 12:48 UTC, d1sam commented on src/main/java/mate/academy/springbootintro/model/Book.java
> +    @ManyToMany()
```suggestion
    @ManyToMany
```

2024-04-23 12:48 UTC, d1sam commented on src/main/java/mate/academy/springbootintro/model/Order.java
> +    private LocalDateTime orderDate;
```suggestion
    @CreationTimestamp
    @Column(name = "order_date", nullable = false)
    private LocalDateTime orderDate;
```

2024-04-23 12:48 UTC, d1sam commented on src/main/java/mate/academy/springbootintro/service/OrderServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-04-24 07:26 UTC, nowickimj requested changes
One thing missing for proper validation

2024-04-24 07:26 UTC, nowickimj commented on src/main/java/mate/academy/springbootintro/controller/OrderController.java
To apply request body validation, use `@Valid`

2024-04-24 07:26 UTC, nowickimj commented on et --hard HEAD~1q
What's that change?

2024-04-24 18:27 UTC, Kalixone commented on et --hard HEAD~1q
I had some problems and decided to use git reset --hard HEAD~1 command, but it was a bad idea, I'm still learning how it all works, but it's all good now i think so

2024-04-25 14:04 UTC, nowickimj commented on et --hard HEAD~1q
Don't use hard reset in your exerices PRs - we want to keep the track of previous commits.

2024-04-25 14:06 UTC, nowickimj approved these changes

2024-05-03 13:42 UTC, merged