spring boot tests
Kalixone/BookstoreAPP pull request #18
Opened 2024-05-03 19:35 UTC by Kalixone

![coverage](https://github.com/Kalixone/BookstoreAPP/assets/138536680/cbcab2d6-e55d-47d6-acd3-4e521c75d631)

2024-05-08 12:52 UTC, d1sam requested changes
Good job, but there are some changes, that should be done!

2024-05-08 12:52 UTC, d1sam commented on src/test/resources/database/categories/add-2-categories-to-categories-table.sql
> +    (2, 'Fantasy', 'Fantasy books', 0);
```suggestion
    (2, 'Fantasy', 'Fantasy books', 0);
    
```

2024-05-08 12:52 UTC, d1sam commented on src/test/resources/database/categories/delete-categories-from-categories-table.sql
> +DELETE FROM categories;
```suggestion
DELETE FROM categories;

```

2024-05-08 12:52 UTC, d1sam commented on src/main/resources/db/changelog/db.changelog-master.yaml
please remove comments.

2024-05-08 12:52 UTC, d1sam commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
please use assertIterableEquals() where it's possible.

2024-05-08 12:52 UTC, d1sam commented on src/test/java/mate/academy/springbootintro/service/CategoryServiceTest.java
please avoid magic numbers and String litterals

2024-05-09 20:15 UTC, Kalixone commented on src/test/java/mate/academy/springbootintro/service/CategoryServiceTest.java
Do i have to add string constants?, because for example in CategoryServiceTest it will be only a few constans, but in BookServiceTest there will be a lot of constants and it will look not clear at all, what should i do?, what is the best practice?

2024-05-10 09:16 UTC, MateuszRostek requested changes
When you take a look at your `CategoryServiceTest` you can see that you use "Horror" and "Scary" in 3 diffrent places - that is not a good approach, you should use 2 constants here and just put them in those places. In BookService take a look at my comment and then think what should be a constant in those methods.

Mentors don't get notifications about comments you post here, if you have any questions about some comments please ask on Mate platform (`pl_jv0_fx_chat`) next time:)

2024-05-10 09:16 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> -        EqualsBuilder.reflectionEquals(expected, actual, "id");
I think you can use this and just call `Assertions.assertIterableEquals(...)` afterwards. No need to compare all fields one by one.

2024-05-10 09:16 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> -        EqualsBuilder.reflectionEquals(expected, actual, "id");
Same here - "I think you can use this and just call `Assertions.assertIterableEquals(...)` afterwards. No need to compare all fields one by one."

2024-05-10 09:16 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/BookServiceTest.java
There is a lot of code repetition in your tests (creating categories/books). Move this logic to private methods (that can take for example 2 params to create diffrent books/categories) and then call this method in appropriate places.

2024-05-13 08:40 UTC, MateuszRostek requested changes
Good job, see some comments, I'm sure you can handle this because you did it in BookControllerTest:)

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> +    private static final String BOOK_SEARCH_AUTHOR = "Rowling";
I don't know exactly what your book model looks like, but you certainly don't need unique values in so many places, you can use the same constant in several places.

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
>          bookDto.setCategoriesIds(Collections.emptyList());
Use `createBookDto` you created.

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> +        expectedBook.setCoverImage(BOOK_COVER_IMAGE_2);
Same here - "Use `createBookDto` you created."

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/CategoryControllerTest.java
> +                CATEGORY_DESCRIPTION_1
You should create and use something similar to `createBookDto` you created in BookControllerTest

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/repository/BookRepositoryTest.java
> +    private static final String EXPECTED_BOOK_TITLE_2 = "Gra o Tron";
Use English names:)

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/BookServiceTest.java
> +        category1.setDescription(CATEGORY_DESCRIPTION_1);
You should create and use something similar to `createBookDto` you created in BookControllerTest

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/BookServiceTest.java
> +        book.setDescription(BOOK_DESCRIPTION);
You should create and use something similar to `createBookDto` you created in BookControllerTest

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/CategoryServiceTest.java
> +        category.setDescription(CATEGORY_DESCRIPTION);
You should create and use something similar to createBookDto you created in BookControllerTest

2024-05-13 08:40 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/BookServiceTest.java
> +        existingBook.setDescription(BOOK_DESCRIPTION);
You should create and use something similar to createBookDto you created in BookControllerTest - in all places:)

2024-05-13 08:42 UTC, MateuszRostek approved these changes

2024-05-13 21:24 UTC, merged