spring boot tests 2
Kalixone/BookstoreAPP pull request #19
Opened 2024-05-14 21:30 UTC by Kalixone

![coverage](https://github.com/Kalixone/BookstoreAPP/assets/138536680/4a324397-a64f-46b1-8f46-f38cf94c27bb)

2024-05-15 08:37 UTC, MateuszRostek requested changes
Nice try, please go through Mate's materials and check how to work with tests.

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/resources/database/users/add-1-user-to-users-table.sql
> +VALUES ('test@example.com', 'testpassword', 'John', 'Travolta', 'street 12', FALSE);
When you add a user to DB, it's better to specify the exact ID he should have.

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/repository/ShoppingCartRepositoryTest.java
> +    }
It should all be in `CustomMySqlContainer` class, with some minor changes. Look at the videos/theoretical part on Mate if you don't know how to do it.

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/repository/ShoppingCartRepositoryTest.java
> +    void findShoppingCartByUserId_ValidUserId_ReturnsShoppingCart() {
What about case for InvalidUserId?

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/repository/ShoppingCartRepositoryTest.java
> +    }
These are redundant.

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/repository/ShoppingCartRepositoryTest.java
> +        assertNotNull(shoppingCart.getCartItems());
You should create `excpeted` shopping cart.

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/ShoppingCartControllerTest.java
> +    }
Same as in Repository tests.

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/ShoppingCartControllerTest.java
> +    }
Also redundant, please refer to Mate materials to check what should be done in the `afterAll` and `beforeAll` methods!

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/ShoppingCartControllerTest.java
> +    private CartItemRepository cartItemRepository;
Shouldn't be used here

2024-05-15 08:37 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/ShoppingCartControllerTest.java
> +    private WebApplicationContext webApplicationContext;
Shouldn't be used here

2024-05-20 08:03 UTC, MateuszRostek requested changes
You did a really good job! See some minor advice:)

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/config/CustomMySqlContainer.java
> +    public CustomMySqlContainer() {
It can still be private,

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/config/CustomMySqlContainer.java
> +        super.stop();
This method can be empty.

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> +    @BeforeEach
I don't think it necessary to do it before each. In all `GET` endpoints you don't make any changes in DB, so it's redundant to teardown then add new books again in these cases.

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> +    public void createBook_ValidRequestDto_CreatesNewBook() throws Exception {
Why did you make those methods public? They should be package-private as they were.

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
> +    public void createBook_ValidRequestDto_CreatesNewBook() throws Exception {
Did you use JUnit4? If so, we can leave it as it is, but let's use JUnit5 next time.

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/CategoryControllerTest.java
> +    @BeforeEach
Same here, I think BeforeAll is better approach, then over some methods (that make changes in DB) let's use `@Sql` like you did earlier.

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/controller/ShoppingCartControllerTest.java
> +                            expectedItem.bookId() + " was not found in the cart"));
You can read how to do it more concisely: https://www.baeldung.com/java-assert-lists-equality-ignore-order

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/ShoppingCartServiceTest.java
> +            );
You can create private methods to create those test objects, then use these methods here to make tests more readable.

2024-05-20 08:03 UTC, MateuszRostek commented on src/test/java/mate/academy/springbootintro/service/ShoppingCartServiceTest.java
> +            );
and then you can re-use these private methods in all your test methods:)

2024-05-21 22:30 UTC, Kalixone commented on src/test/java/mate/academy/springbootintro/controller/BookControllerTest.java
Before all I deleted liquibase to have a clean database, then I didn't add scripts everywhere, but where necessary, but I don't know if I did it correctly, I also changed the methods from public to default as you wrote to me

2024-05-21 22:32 UTC, Kalixone commented on src/test/java/mate/academy/springbootintro/config/CustomMySqlContainer.java
I changed the constructor to private and got rid of the implementation of the stop method

2024-05-21 22:33 UTC, Kalixone commented on src/test/java/mate/academy/springbootintro/controller/CategoryControllerTest.java
Changed from BeforeEach to BeforeAll and used Sql scripts

2024-05-21 22:34 UTC, Kalixone commented on src/test/java/mate/academy/springbootintro/controller/ShoppingCartControllerTest.java
Created private methods to make the code more readable

2024-05-22 07:51 UTC, MateuszRostek approved these changes
Good job, approved! I have some comment that you should consider when working with tests:


I think it would be better to add these 3 basic books with the script you have in the `@BeforeAll` method after cleaning the DB, then use `Sql` annotation only over methods that changes something in DB.

So for example in the `createBook_ValidRequestDto_CreatesNewBook()` you should use this Sql annotation with AFTER.METHOD execution phase and there you can just deleted this newly created book (Or just clean whole books table and add these 3 books again). Then you don't have to use Sql annotation on your GET test methods.
You should keep the DB the same after each test method, so for example when you delete book by id, you should add it afterwards.

2024-05-22 15:22 UTC, merged